# Generated by Django 5.1.5 on 2025-03-05 22:00

import useraccount.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[useraccount.validators.validate_contact_number]),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[useraccount.validators.validate_date_of_birth]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[useraccount.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255, validators=[useraccount.validators.validate_full_name]),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/avatars', validators=[useraccount.validators.validate_profile_picture]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor'), ('admin', 'Admin')], default='student', max_length=10, validators=[useraccount.validators.validate_role]),
        ),
    ]
