# Generated by Django 5.1.5 on 2025-04-01 05:29

import useraccount.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_user_accept_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accept_terms',
            field=models.BooleanField(default=False, validators=[useraccount.validators.accept_terms_check]),
        ),
    ]
