# Generated by Django 5.1.5 on 2025-03-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/courses'),
        ),
    ]
