# Generated by Django 5.1.5 on 2025-03-18 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='profile_picture',
            new_name='course_picture',
        ),
    ]
