# Generated by Django 5.1.5 on 2025-03-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_rename_profile_picture_course_course_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='demo_url',
            field=models.TextField(default='https://youtu.be/5Xy-t8k_M4A?si=f3VnWw4mQRngGHW0'),
            preserve_default=False,
        ),
    ]
