# Generated by Django 5.1.5 on 2025-03-21 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_studentprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='module',
            name='completed',
        ),
    ]
