# Generated by Django 5.1.5 on 2025-03-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_remove_lesson_completed_remove_module_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
