# Generated by Django 5.1.5 on 2025-03-21 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_lesson_completed_module_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='module',
            name='completed',
        ),
    ]
