# Generated by Django 5.1.5 on 2025-03-21 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_studentprogress_unique_together_mcqquestion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcqquestion',
            old_name='correct_answer_index',
            new_name='correct_Option_index',
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Option_text', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Options', to='course.mcqquestion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
