# Generated by Django 5.1.5 on 2025-03-24 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_rename_correct_answer_index_mcqquestion_correct_option_index_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcqquestion',
            old_name='correct_Option_index',
            new_name='correct_option_index',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='Option_text',
            new_name='option_text',
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='course.mcqquestion'),
        ),
    ]
