# Generated by Django 5.1.5 on 2025-04-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_remove_studentprogress_lesson_quizresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='quizresult',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
