# Generated by Django 5.1.5 on 2025-04-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_remove_quizresult_submitted_at_quizresult_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='submission_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
