# Generated by Django 5.1.5 on 2025-04-11 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_quizresult_submission_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('date', models.DateField(blank=True, null=True)),
                ('join_link', models.URLField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='ClassResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='class_resources/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='course.courseclass')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_url', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='course.courseclass')),
            ],
        ),
    ]
