# Generated by Django 5.1.5 on 2025-04-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_courseclass_classresource_classrecording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseclass',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
