# Generated by Django 5.1.5 on 2025-04-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_course_instructor'),
        ('useraccount', '0005_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(related_name='courses', to='useraccount.instructor'),
        ),
    ]
