# Generated by Django 5.1.5 on 2025-04-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_remove_course_instructor_course_instructors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bannerdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.CharField(max_length=255)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='uploads/bannner')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
