# Generated by Django 5.1.5 on 2025-04-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_enrollment_payment_status_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='certificate_download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='certificate_issue_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('bkash', 'BKash'), ('nagad', 'Nagad'), ('bank_transfer', 'Bank Transfer')], default='bkash', max_length=50),
        ),
    ]
